# Generated by Django 5.2.10 on 2026-01-08 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TeaserQuestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quiz_name", models.CharField(max_length=100, verbose_name="퀴즈명")),
                (
                    "user_answer",
                    models.CharField(max_length=200, verbose_name="사용자 답변"),
                ),
                ("is_correct", models.BooleanField(verbose_name="정답 여부")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="참여일시"),
                ),
            ],
            options={
                "verbose_name": "퀴즈 기록",
                "verbose_name_plural": "퀴즈 기록 목록",
            },
        ),
        migrations.CreateModel(
            name="PreRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, unique=True, verbose_name="이메일"),
                ),
                (
                    "referral_code",
                    models.CharField(max_length=8, unique=True, verbose_name="추천 코드"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="가입일시"),
                ),
                (
                    "referred_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referrals",
                        to="landing.preregistration",
                        verbose_name="추천인",
                    ),
                ),
            ],
            options={
                "verbose_name": "사전 예약",
                "verbose_name_plural": "사전 예약 목록",
            },
        ),
    ]
