# Generated by Django 5.2.10 on 2026-01-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="preregistration",
            name="age_group",
            field=models.CharField(blank=True, max_length=10, verbose_name="연령대"),
        ),
        migrations.AddField(
            model_name="preregistration",
            name="marketing_agreed",
            field=models.BooleanField(default=False, verbose_name="마케팅 수신 동의"),
        ),
        migrations.AddField(
            model_name="preregistration",
            name="phone",
            field=models.CharField(blank=True, max_length=20, verbose_name="전화번호"),
        ),
        migrations.AddField(
            model_name="preregistration",
            name="privacy_agreed",
            field=models.BooleanField(default=False, verbose_name="개인정보 수집 동의"),
        ),
        migrations.AddField(
            model_name="preregistration",
            name="region",
            field=models.CharField(blank=True, max_length=20, verbose_name="거주 지역"),
        ),
    ]
