# Generated by Django 5.2.10 on 2026-01-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landing", "0002_preregistration_age_group_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="퀘스트명")),
                ("description", models.TextField(verbose_name="설명")),
                (
                    "icon",
                    models.CharField(
                        help_text="이모지 또는 아이콘 클래스", max_length=50, verbose_name="아이콘"
                    ),
                ),
                (
                    "is_starter_pack",
                    models.BooleanField(default=False, verbose_name="스타터팩 포함 여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
            ],
            options={
                "verbose_name": "퀘스트",
                "verbose_name_plural": "퀘스트 목록",
            },
        ),
    ]
